### ISSUE TITLE
Seeking causes entire stream to be fetched

### ISSUE THREAD

**Issue by christosk92** [NVorbis/NVorbis#38] opened 2023-08-03 13:14 UTC
This is particularly killing for apps that rely on web streaming (which is the case for me), as it has to fetch all chunks for even a couple of seconds of seeking. 

Upon inspecting the source code, it seems that the "TotalSamples" property might be the culprit, which calls the "GetGranuleCount" function, which in turn fetches all the pages. 
>
```cs
 public long GetGranuleCount()
        {
            if (_reader == null) throw new ObjectDisposedException(nameof(PacketProvider));

            if (!_reader.HasAllPages)
            {
                // this will force the reader to attempt to read all pages
                _reader.GetPage(int.MaxValue, out _, out _, out _, out _, out _, out _);
            }
            return _reader.MaxGranulePosition.Value;
        }
```   

I'll try to look into maybe using some kind of bisection method to seek to the correct position without having to fetch all the pages, but I am in no way an expert in audio processing etc, so any help would be appreciated.

**Comment by christosk92** [comment] 2023-08-03 13:37
I was actually able to kinda fix this by removing some TotalLength checks in the setter of the Position.

Still, seeking to the end of a stream, causes the seeking to find the correct page in a sequential manner, rather than; let's say bisection. 

Is there any way we can resolve this issue?

Thanks!

**Comment by ioctlLR** [comment] 2023-08-03 14:28
Can you share how you are using NVorbis for this?  A minimal repro project would be great.  Thanks!

**Comment by christosk92** [comment] 2023-08-03 16:11
> Can you share how you are using NVorbis for this? A minimal repro project would be great. Thanks!

Thanks for your reply. 

Basically what I’m doing is creating a custom System.IO stream, this stream fetches encrypted audio chunks from a url using a HttpClient and decrypts them using a very custom algorithm. 

It’s getting kinda late here so I’ll try to make a reproducible app tomorrow.

**Comment by barkermn01** [comment] 2023-08-07 21:01
This might be not be 100% related to this but your getting encrypted audio chunks, could i aske why you used a HttpClient and not a WebSocket if your streaming data it will be much more efficient, and might help a little with your re-downloading but i would agree that your better trying to get a bisect working. 

Would love to see a repro app that may be able to help with that, as i have some experience in streaming tech but in the mean time could i confirm your chunks are around the "Ogg page"? as that's the way this should complete https://en.wikipedia.org/wiki/Ogg_page (you may know this im also putting it here for future references)

**Comment by christosk92** [comment] 2023-08-08 01:19
@barkermn01 well I have no control over the architecture, it’s a third party music streaming service. They host their audiofiles on a cdn which are encrypted using an algorithm. I will try to get a reproducible sample but ive been kinda busy with work. I’ll try to get one today

**Comment by christosk92** [comment] 2023-08-08 01:53
@Barkermn01 @ioctlLR I've extracted the core components from my code (its literally the same code), but i've replaced the audio fetching with a FileStream that has a delay of 200ms for every chunk fetch.
https://github.com/christosk92/NVorbis_ReproSample

**Comment by barkermn01** [comment] 2023-08-08 12:29
Thanks i will have a look as soon as i can, i know the busy with work thing myself :D

**Comment by ioctlLR** [comment] 2023-08-08 17:39
@christosk92 OK, the problem you're encountering is due to [this line](https://github.com/christosk92/NVorbis_ReproSample/blob/main/NAudioReproducibleSample.Console/Program.cs#L83).  Instead of asking NVorbis for that information, download the metadata for the audio stream and use the value from there.

There are only two ways to get the duration of an Ogg Vorbis audio stream: Read the granulePos of the last page in the stream (which in your case implies downloading the entire stream), OR get the duration from an external source.  As far as I know there are no other options.

**Comment by christosk92** [comment] 2023-08-08 18:03
@ioctlLR Right, well I can fix that (since I do know the total duration). That fixes the fetching the entire stream part.

The next issue is that seeking to an arbitrary position, causes ALL chunks leading up to that position to be fetched. So if a user seeks to for example 80%, almost the entire track has to be fetched, instead of doing some kind of bisection to find the correct page.

This does not occur in the UWP MediaPlayer, but it has its own issues so I can't really use that one.

**Comment by ioctlLR** [comment] 2023-08-08 18:22
Yeah...  So when I designed the newest Ogg reader I built it to cache page header locations (and granules) to make seeking faster, assuming anything streamed wouldn't be seek-able anyway (there's a different IPacketProvider implementation for that).  I don't think I ever expected a scenario where a streamed datasource would need to be seek-able.

Feel free to fork and modify the Ogg/PageReader & Ogg/PacketProvider types (or write your own) to support your specific scenario (I'll take a PR if you're interested!).  That said, I think you're better off actually implementing your own IPacketProvider that understands "seeking" the source datastream.  I'm pretty sure there's enough in the existing code it shouldn't be overly difficult.

**Comment by christosk92** [comment] 2023-08-08 18:24
Thanks! I’ll be sure to take a look and try and get it working for my use case. I agree it’s a very specific use case and most people just use a file system source. Thanks for your help

**Comment by ioctlLR** [comment] 2023-08-09 20:08
Awesome!  And if you do happen to create a PR I'll be happy to work on it with you.  Until then I'm going to close this item.

**Closed as completed by ioctlLR** 2023-08-09 20:08 UTC
Labels: invalid

**Comment by christosk92** [comment] 2023-08-11 05:23
Short update:

I've managed to modify the code to fetch the latest page in the stream, and then calculating it granulepos to calculate the total time without fetching the whole stream.

It's my first time doing audio processing etc, but from what I've read online, I did the following:

- Seek to the end of the stream, MINUS one OGG page. 
- Seek forward byte by byte until we find the OggS header AND until end of stream.
- Since one vorbis page might be smaller than the max size, seeking until the end of the stream allows us to find even the smallest pages. 
- Use existing functions to add the page to the collection, which updates the maxgranulepos.


Next I'll try to implement bisection search (https://wiki.xiph.org/GranulePosAndSeeking)

**Comment by barkermn01** [comment] 2023-08-11 22:53
@christosk92 
your point 2 should not be needed If you have jumped to the last page of the stream, the first set of 4 bytes so bytes 0 to 3 (inclusive) should be the "OggS" `4F676753` Capture it's required to be there as part of the Ogg Spec.

After that you can seek to 24 bytes (seek forward by 21 from the end of the last read) read the next 4 bytes that will be the number of page segments then minus 1 from that then times it by 255 (the largest size a segment can be and will be unless it's the last) lets call this offset for ease, and finally seek forward by offset, your now at the last page and at the last segment seek forward until end to read end of page.

**Comment by christosk92** [comment] 2023-08-13 04:55
Well I know this might sound stupid but I just went ahead and made a whole new decoder (new project) since it was really hard for me to modify the existing code. 

I ported symphonia(https://github.com/pdeljanov/Symphonia) from rust into c# and it works well. 
<img width="1276" alt="image" src="https://github.com/NVorbis/NVorbis/assets/13438702/f87ec40d-c878-48b7-a121-882d9323d154">


If anyone's interested, i'll be looking to publish it to github once it's ready,

**Comment by christosk92** [comment] 2023-08-13 06:35
https://github.com/christosk92/WaveeVorbis
